### ISSUE TITLE
识别的正确率怎么估计出来的？已经实现了吗？

### ISSUE THREAD

**Issue by fancymax** [jinhang/12306_captcha#1]
深度学习

学习深度学习后，使用基于thneano的keras可以构建卷积神经网络进行识别，用爬虫从sina和百度上做好样本后，编码实现网络，得到合适的训练的模型，效果还不错，调整参数和加大样本后，**正确率估计**达到0.92以上。
样本分为文本和图片

**Comment by jinhang** [comment]
不知道你说的是哪个？基本已经训练出了模型，可以完成识别，训练样本越多准确率越高。
